/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cronometro;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author andre
 */
public class Cronometro extends javax.swing.JFrame {

    /**
     * Creates new form Cronometro
     */

    public Cronometro() {
        initComponents();
    }

    /**
     * int Quan This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // End of variables declaration     

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        resultadoEsquerda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        resultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("00");

        resultadoEsquerda.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        resultadoEsquerda.setForeground(new java.awt.Color(255, 255, 255));
        resultadoEsquerda.setText("00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(":");

        Voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Voltar.setText("Zerar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Iniciar.setBackground(new java.awt.Color(102, 255, 0));
        Iniciar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Iniciar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(resultadoEsquerda)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(resultado)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado)
                    .addComponent(resultadoEsquerda)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar)
                    .addComponent(Iniciar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int QuanridadeDeClicks = 0;
    boolean pediuParada = false;
    int ClickZerar = 0;
    int segundos = 0;
    int minutos = 0;

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
    	
        
        Thread cronometro = new Thread(new Runnable() {
            public void run(){
                //Parte criada para o quando o botao "Zerar" for acionado
                if(ClickZerar == 1){
                pediuParada = false;
                segundos = 0;
                minutos = 0;
                ClickZerar = 0;
                }
                //FIM
                for(; segundos <= 60; segundos++) {
                	if(pediuParada) {
                		pediuParada = false;
                		break;
                	}
                	
                    if(segundos < 10) {
                        resultado.setText( String.valueOf("0"+segundos) );
                        
                    } else {
                        resultado.setText( String.valueOf(segundos) );
                    }
                    //Aumentando os minutos
                    //parte para adicionar os minutos
                    if(segundos == 60){
                        segundos = 0;
                        minutos++;
                        
                        if(segundos < 10) {
                            resultado.setText( String.valueOf("0"+segundos) );
                        } else {
                            resultado.setText( String.valueOf(segundos) );
                        }
                        
                        if(minutos < 10) {
                        	resultadoEsquerda.setText(String.valueOf("0" + minutos));
                        } else {
                        	resultadoEsquerda.setText(String.valueOf(minutos));
                        }
                    }
                    
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                
                
            }    
        });
 
        //Variavel
        if(QuanridadeDeClicks == 0){
        	Iniciar.setBackground(Color.red);
        	cronometro.start();
	        
	        Iniciar.setText("Parar");
                QuanridadeDeClicks = 1;
	        
        } else if (QuanridadeDeClicks == 1){
                Iniciar.setBackground(Color.green);
        	QuanridadeDeClicks = 0;
        	pediuParada = true;
        	Iniciar.setText("Retomar");
        }
            
        
   
    }//GEN-LAST:event_IniciarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        resultadoEsquerda.setText(String.valueOf("0"+0));
        resultado.setText(String.valueOf("0"+0));
        pediuParada = true;
        QuanridadeDeClicks = 0;
        ClickZerar = 1;
        
        
    }//GEN-LAST:event_VoltarActionPerformed

    public static void time() {
        try {
            Thread.sleep(1000);
        } catch (Exception ex) {

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronometro().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultadoEsquerda;
    // End of variables declaration//GEN-END:variables

}
